/**
 * device-type-help.ts — pre-baked inline help text for each device_type value.
 *
 * One paragraph per type. Rendered as an inline help card below the device type
 * dropdown in the Discover flow — NOT a tooltip, NOT a side panel.
 *
 * Text is pre-baked (not runtime LLM-generated). Written for Aaron's context:
 * off-grid microgrid operator in Uganda configuring a single-phase residential grid.
 */

import type { DeviceType } from "@/lib/types/domain";

export type DeviceTypeHelp = {
  /** Short label for display in the dropdown option list. */
  label: string;
  /** One paragraph of inline help shown below the dropdown. */
  description: string;
};

export const DEVICE_TYPE_HELP: Record<DeviceType, DeviceTypeHelp> = {
  consumption_meter: {
    label: "Consumption meter",
    description:
      "Measures electricity used by a specific household or load point. This is the device type you assign to households for billing — each household should have exactly one primary consumption meter so their usage can be calculated and invoiced each period.",
  },
  grid_meter: {
    label: "Grid meter",
    description:
      "Measures electricity flowing between your microgrid and the utility grid (import and export). This is a site-level meter — it tracks how much the microgrid buys from or sells to the grid, not individual household usage. Do not assign a grid meter to a household for billing.",
  },
  pv_meter: {
    label: "PV meter",
    description:
      "Measures electricity generated by solar panels or another production source. This is a generation meter — it shows how much power your solar array is producing. It is not typically assigned to a household for billing, but helps you track self-generation vs. grid import.",
  },
  battery: {
    label: "Battery",
    description:
      "Represents a battery energy storage system (ESS). A battery stores excess solar production and discharges to supply the microgrid at night or during low-generation periods. Battery devices are not billed directly but are important for understanding your microgrid's self-sufficiency.",
  },
  inverter: {
    label: "Inverter",
    description:
      "A power conversion device that converts DC (from solar or batteries) to AC for your microgrid loads. Inverters are infrastructure components — they are not assigned to households for billing but may be monitored for efficiency and fault detection.",
  },
  ev_charger: {
    label: "EV charger",
    description:
      "An electric vehicle charging station connected to the microgrid. EV chargers are controllable loads — they can be scheduled or throttled to avoid overloading the grid during peak demand. If the EV charger bills per session, it may be assigned to a household.",
  },
  other: {
    label: "Other",
    description:
      "This device type did not match a known category. Use 'Other' when the component serves a purpose not covered by the types above (for example, a relay, sensor, or controller). You can always change the type later from the device list.",
  },
};
