-- supabase/seed.sql — intentionally empty.
--
-- After the entity-model rewrite (AB ticket #50), seeded auth.users + user_roles are
-- embedded in the migration supabase/migrations/00003_seed.sql (generated at setup
-- time by envsubst from 00003_seed.sql.template). See setup.sh for details.
