_format_version: "3.0"
services:
  - name: auth
    url: http://gotrue:9999
    routes:
      - name: auth-route
        paths: ["/auth/v1/"]
        strip_path: true
  - name: rest
    url: http://postgrest:3000
    routes:
      - name: rest-route
        paths: ["/rest/v1/"]
        strip_path: true
plugins:
  - name: cors
    config:
      origins: ["http://localhost:3000"]
      methods: [GET, POST, PUT, PATCH, DELETE, OPTIONS]
      headers: [Authorization, Content-Type, apikey, x-client-info, x-supabase-api-version]
      exposed_headers: [X-Total-Count, Link, X-Supabase-Api-Version]
      credentials: true
