/**
 * Human-readable descriptions for device types discovered from OpenEMS.
 *
 * Keyed by the discovery classification string (GRID | PRODUCTION | CONSUMPTION | UNKNOWN)
 * as well as the lowercase device_type enum values from AB #50 (grid_meter, pv_meter, etc.).
 *
 * Renamed from meter-descriptions.ts → device-descriptions.ts (entity-model migration C #51).
 * Extended in F #57 to include lowercase device_type keys so callers can use either form.
 */
export const DEVICE_TYPE_INFO: Record<
  string,
  { label: string; shortDesc: string; billingHint: string }
> = {
  // Uppercase legacy keys (from old classifyDeviceType — kept for backward compatibility)
  GRID: {
    label: "Utility Connection",
    shortDesc:
      "Measures electricity flowing between your microgrid and the utility grid.",
    billingHint: "Not typically assigned to households — measures the whole site.",
  },
  PRODUCTION: {
    label: "Solar / Generator",
    shortDesc:
      "Measures electricity generated by a power source like solar panels.",
    billingHint:
      "Not typically assigned to households — measures generation, not consumption.",
  },
  CONSUMPTION: {
    label: "Household Load",
    shortDesc:
      "Measures electricity used by a specific load, building, or household.",
    billingHint: "Assign this device type to households for billing.",
  },
  UNKNOWN: {
    label: "Unclassified",
    shortDesc: "Could not determine device type automatically.",
    billingHint:
      "Verify the device's purpose before assigning to a household.",
  },

  // Lowercase device_type enum keys (canonical — from AB #50 schema, F #57 classify.ts)
  grid_meter: {
    label: "Grid meter",
    shortDesc:
      "Measures electricity flowing between your microgrid and the utility grid.",
    billingHint: "Not typically assigned to households — measures the whole site.",
  },
  pv_meter: {
    label: "PV meter",
    shortDesc:
      "Measures electricity generated by solar panels or another production source.",
    billingHint:
      "Not typically assigned to households — measures generation, not consumption.",
  },
  consumption_meter: {
    label: "Consumption meter",
    shortDesc:
      "Measures electricity used by a specific load, building, or household.",
    billingHint: "Assign this device type to households for billing.",
  },
  battery: {
    label: "Battery",
    shortDesc: "Energy storage system (ESS) storing excess solar and discharging at night.",
    billingHint: "Not directly billed but tracked for self-sufficiency reporting.",
  },
  inverter: {
    label: "Inverter",
    shortDesc: "Power conversion device converting DC to AC for microgrid loads.",
    billingHint: "Infrastructure component — not assigned to households for billing.",
  },
  ev_charger: {
    label: "EV charger",
    shortDesc: "Electric vehicle charging station connected to the microgrid.",
    billingHint: "May be assigned to a household if billing per session.",
  },
  other: {
    label: "Other",
    shortDesc: "Device type not covered by the known categories.",
    billingHint: "Verify the device's purpose before assigning to a household.",
  },
};

// Legacy export alias to ease any lingering references during migration.
/** @deprecated Use DEVICE_TYPE_INFO */
export const METER_TYPE_INFO = DEVICE_TYPE_INFO;

/**
 * humanReadable — return the human-readable label for a device-type enum value
 * (or any legacy uppercase classification key). Falls back to the raw key if
 * unknown so callers never render `undefined`.
 *
 * Example:
 *   humanReadable("consumption_meter") // "Consumption meter"
 *   humanReadable("grid_meter")        // "Grid meter"
 */
export function humanReadable(deviceType: string | null | undefined): string {
  if (!deviceType) return "Unclassified";
  const entry = DEVICE_TYPE_INFO[deviceType];
  if (entry) return entry.label;
  // Secondary lookup: try uppercase fallback (legacy keys).
  const upper = DEVICE_TYPE_INFO[deviceType.toUpperCase()];
  if (upper) return upper.label;
  return deviceType;
}
