/**
 * Human-readable descriptions for device types discovered from OpenEMS.
 *
 * Keyed by the discovery classification string (GRID | PRODUCTION | CONSUMPTION | UNKNOWN).
 * These are OpenEMS factory-derived device classifications, NOT the database device_type enum.
 *
 * Renamed from meter-descriptions.ts → device-descriptions.ts (entity-model migration C #51).
 */
export const DEVICE_TYPE_INFO: Record<
  string,
  { label: string; shortDesc: string; billingHint: string }
> = {
  GRID: {
    label: "Utility Connection",
    shortDesc:
      "Measures electricity flowing between your microgrid and the utility grid.",
    billingHint: "Not typically assigned to households — measures the whole site.",
  },
  PRODUCTION: {
    label: "Solar / Generator",
    shortDesc:
      "Measures electricity generated by a power source like solar panels.",
    billingHint:
      "Not typically assigned to households — measures generation, not consumption.",
  },
  CONSUMPTION: {
    label: "Household Load",
    shortDesc:
      "Measures electricity used by a specific load, building, or household.",
    billingHint: "Assign this device type to households for billing.",
  },
  UNKNOWN: {
    label: "Unclassified",
    shortDesc: "Could not determine device type automatically.",
    billingHint:
      "Verify the device's purpose before assigning to a household.",
  },
};

// Legacy export alias to ease any lingering references during migration.
/** @deprecated Use DEVICE_TYPE_INFO */
export const METER_TYPE_INFO = DEVICE_TYPE_INFO;
