export const METER_TYPE_INFO: Record<string, { label: string; shortDesc: string; billingHint: string }> = {
  GRID: {
    label: "Utility Connection",
    shortDesc: "Measures electricity flowing between your microgrid and the utility grid.",
    billingHint: "Not typically assigned to tenants — measures the whole site.",
  },
  PRODUCTION: {
    label: "Solar / Generator",
    shortDesc: "Measures electricity generated by a power source like solar panels.",
    billingHint: "Not typically assigned to tenants — measures generation, not consumption.",
  },
  CONSUMPTION: {
    label: "Tenant Load",
    shortDesc: "Measures electricity used by a specific load, building, or tenant.",
    billingHint: "Assign this meter type to tenants for billing.",
  },
  UNKNOWN: {
    label: "Unclassified",
    shortDesc: "Could not determine meter type automatically.",
    billingHint: "Verify the meter's purpose before assigning to a tenant.",
  },
};
